
#spring:
#  profiles:
#    active: prod
#
#---
#spring:
#  profiles: dev
#
#server:
#  port: 8089
#
#---
#spring:
#  profiles: prod
#server:
#  port: 8090
#
#---
#spring:
#  profiles: uat
#server:
#  port: 8080

